### ISSUE TITLE
Pre-populate the  input field with mask

### ISSUE THREAD

**Issue by anudwigna** [probil/v-mask#36]
Cannot pre-populate the input field where the mask is being used. 
Also does not work while trying to set the model value for the mask.

**Comment by probil** [comment]
@anudwigna Can you provide some code and/or example of your issue?

**Comment by jpozosrc** [comment]
I am having the same issue. When i load my view in 'add mode' (my model's properties are null or empty) masking works as expected.
However, when I load my view in 'edit mode' (my model's properties have values)

Here's the markup

`<input 
    name="phone" 
    v-model="viewModel.phone"
    class="form-control" 
    mask="'(###)-###-####'" />`

**Comment by jpozosrc** [comment]
I think the problem is on function updateValue().
I debugged it and when I made the change below, it works when the view model property is prepopulated

`function updateValue(el) {
  var force = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : false;
  var value = el.value,
      _el$dataset = el.dataset,
      _el$dataset$previousV = _el$dataset.previousValue,
      **//previousValue = _el$dataset$previousV === undefined ? "" : _el$dataset$previousV,
      previousValue = (_el$dataset$previousV === undefined || _el$dataset$previousV === null) ? "" : _el$dataset$previousV,**
      mask = _el$dataset.mask;

  if (force || value && value !== previousValue && value.length > previousValue.length) {
    el.value = (0, _format2.default)(value, mask);
    (0, _utils.trigger)(el, 'input');
  }

  el.dataset.previousValue = value;
}`

**Comment by probil** [comment]
> In the code below, if viewModel.phone has a value when the view renders, it throws error:
> Cannot read property 'length' of null

Thanks for that. I will try to reproduce and fix the issue

**Comment by jpozosrc** [comment]
Thanks a lot!
