### ISSUE TITLE
:v-mask not working on binding

### ISSUE THREAD

**Issue by zefexdeveloper** [probil/v-mask#458]
I created a wrapper component for the input and asked for a prop called `mask`. I tried to pass that prop to the input with the mask as `:v-mask="mask"` but it's not working.

```js
        <input
            class="form-input"
            type="text"
            :v-mask="mask"
            :value="value"
            @input="update"
        />
```

The DOM is showing that the `v-mask` was binded:

![image](https://user-images.githubusercontent.com/30276092/69011898-654f0d00-094e-11ea-90d4-57c4832e89dd.png)

But it's not working.

**Comment by probil** [comment]
Hi, @zefexdeveloper 👋 

You shouldn't add `:` at the beginning of the `v-mask` directive. E.g.

```html
<input
  class="form-input"
  type="text"
  v-mask="mask"
  :value="value"
  @input="update"
/>

**Comment by zefexdeveloper** [comment]
Thank you for the answer @probil 

In my case I wanted to create a `FormInput` component wrapping the `input` and passing down the mask prop, the problem is that without `:` is makes the prop required automatically, so that is a problem.

**Comment by sajuthankathurai** [comment]
v-mask not working if I have :value instead of v-model. Sample JS fiddle : https://jsfiddle.net/ozdnqswy/8/ 

**Not working**
<input type="text" :maxLength="16" v-mask="'#### #### #### ####'" :value="inputVal" :placeholder="placeholder">

**Working**
<input type="text" :maxLength="16" v-mask="'#### #### #### ####'" v-model="inputVal" :placeholder="placeholder">

**Comment by probil** [comment]
@JohnWeidmann Can you tell me more about the issue? Preferably as a new issue
